### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Mambix** [NanoBjorn/yobit#1]
@NanoBjorn 

I will use this in my project but there is no license attached. Is that intentional?
I also want to refactor the project so that I can push it to pypi. You OK with that?

**Comment by NanoBjorn** [comment]
Hello!

I was doing without any license. You can just mention my github in documentation:)

**Comment by Mambix** [comment]
Ok will do that but for PyPi I will stick a MIT license to my repo if you're OK with that.

**Comment by NanoBjorn** [comment]
I’m OK, great!

**Comment by Mambix** [comment]
@NanoBjorn 

You should now be able to do this:
`pip install YoBit`  

And then use it in your code:  
```Python
from YoBit import YoBit

yb = YoBit(api_key='YOUR_API_KEY', api_secret='YOUR_API_SECRET')
yb.get_info()
```

**Comment by NanoBjorn** [comment]
That’s great!

**Comment by NanoBjorn** [comment]
You’ve used wrong link (`githun` instead of `github`) in the README file, fit it please:)

**Comment by Mambix** [comment]
good catch, fixed :+1:
